---
- name: Stop and remove Docker containers
  command: docker-compose down
  args:
    chdir: /opt/web_app
  when: web_app_full_wipe

- name: Remove Docker Compose file
  file:
    path: /opt/web_app/docker-compose.yml
    state: absent
  when: web_app_full_wipe