---
- hosts: all
  become: yes
  roles:
    - role: web_app
      vars:
        docker_image: "sonyaiv/python_app:latest"
        docker_container: "python_app"
        docker_compose_filename: "docker-compose.yml"

        web_app_dir: "/webapp"

        internal_port: 8000
        external_port: 80

        web_app_full_wipe: true
    