---
- name: Install Docker
  include_tasks: install_docker.yml

- name: Install Docker Compose
  include_tasks: install_compose.yml

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes